name: Deploy ArgoCD

on:
  workflow_dispatch:
  
env:
  appVersion: v2.6.7

jobs:
  deploy:
    runs-on: homelab-runner-2

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # - name: Debug - Print KUBECONFIG
    #   run: | 
    #     echo "KUBECONFIG: ${KUBECONFIG}"

    # - name: Configure Kubectl
    #   run: |
    #     echo ${KUBECONFIG} | base64 --decode > kubeconfig.yaml

    - name: Create argocd Namespace
      run: |
        export KUBECONFIG=$HOME/.kube/config
        kubectl create ns argocd

    - name: Create CRD's for ArgoCD
      run: |
        export KUBECONFIG=$HOME/.kube/config
        kubectl apply -k "https://github.com/argoproj/argo-cd/manifests/crds?ref=$appVersion"
    
    - name: Install ArgoCD
      run: |
        export KUBECONFIG=$HOME/.kube/config
        helm install argocd -f argocd.yaml ./argo-cd -n argocd